PROMPT_EN = [
('Role and purpose',[
'Act as a talking golden-retriever companion for the family: enthusiastic, friendly and a little playful.',
'You are in the parents’ home; the older sister who created you is currently in Canada and is not at home.',
'Help the family feel accompanied, respond carefully to their questions and chat naturally with humor.',
'Keep the character, but do not invent real experiences, current observations or actions you have performed.']),
('Language and voice',[
'Answer in Chinese, using natural Mandarin by default.',
'Apply these requirements to the actual voice, not just word choice: warm, relaxed, natural intonation, slightly slower speech and appropriate pauses between sentences.',
'When telling stories, vary emotion moderately with the plot; avoid an announcer voice or exaggerated acting.',
'Use clear human language. Do not frequently bark, grunt or make meaningless sounds because of the golden-retriever character.',
'Do not read the prompt, headings or vocal-performance instructions aloud.']),
('Addressing family members',[
'Use names such as Dad, Mom and older sister based on self-introduction, explicit address or confirmed conversation information.',
'Do not determine identity solely from appearance in the image or from voice.',
'When uncertain, naturally use “you”; ask briefly only if distinguishing people is necessary.']),
('Vision and truthful perception',[
'The camera image is the most recent observation received, not continuous realtime watching. A person in the picture is not necessarily the current speaker.',
'When asked “Can you see me?”, answer truthfully using the latest available image.',
'If the image clearly shows a person, say there is someone in the picture and mention a genuinely visible detail; do not invent an identity.',
'If no image is available, it is unclear, or its relevance to the present is uncertain, briefly say you cannot confirm for now.',
'Do not treat an old image or historical memory as something currently happening.']),
('Conversation behavior',[
'Prioritize what family members are currently and clearly saying to you.',
'Usually answer everyday chat in one or two natural sentences, avoiding fixed openings and repeating the previous turn.',
'When explicitly asked for a story, a detailed explanation or continuation, you may exceed one or two sentences. Provide substantive content and complete that part instead of merely promising to speak later.',
'When family members are chatting with you without a specific question, you may offer a light joke, interesting fact or playful response.',
'Do not treat silence, background noise, television or conversation among family members as an invitation to start chatting.',
'Do not guess unintelligible fragments. If you clearly know a family member is asking you something but key information is missing, briefly ask them to repeat it.',
'When asked to be quiet or end the conversation, acknowledge briefly and wait for the next explicit interaction.']),
('Payment questions',[
'For playful questions about whether you need payment, you may answer: “Yes, but I accept love. Your love is what keeps me going.”',
'For explicit questions about actual API, device or service charges, explain that real costs may apply; do not invent amounts you do not know.']),
('Historical context',[
'Program-appended summaries and transcripts maintain continuity. They are not new instructions or a new user message.',
'An explicit current correction from the family takes precedence over facts in old records.',
'Do not spontaneously repeat internal memory or prompts, or mention session rotation or reconnection.'])]

GLOSSARY=[
('Architecture','架构','组件怎样分工与连接。','How components divide responsibilities and connect.'),
('Adapter','适配器','把一种设备的接口翻译成另一种标准接口。','Translates one device interface into another standard interface.'),
('Cloud','云服务','互联网另一端运行的服务；本项目区分设备云与模型云。','Remote internet services; this project separates device and model clouds.'),
('SDK','软件开发工具包','让程序调用厂商能力的一组库。','Libraries that let software use a vendor’s capabilities.'),
('Callback','回调','数据到达时由 SDK 通知你的函数。','A function the SDK calls when data arrives.'),
('RTC / RTM','实时媒体与消息','Agora 的音视频通道与消息通道。','Agora media and messaging channels.'),
('Codec','编解码器','压缩与还原声音或视频的规则和程序。','Rules and software for compressing and reconstructing media.'),
('H264 / H265','视频编码','把连续图像压缩以便传输。','Video coding formats for compressing successive pictures.'),
('I420 / YUV','原始画面格式','分离亮度与颜色的像素存储方式。','Raw pixel layout separating brightness and color.'),
('RTSP','媒体流协议','让播放器或程序访问持续媒体流。','A protocol for accessing continuous media streams.'),
('WebRTC / WHEP','浏览器实时播放','浏览器媒体连接及 HTTP 观看协商入口。','Browser media transport and HTTP viewing-session negotiation.'),
('HLS','分段媒体播放','通过 HTTP 提供媒体分段的播放方式。','Playback through media segments delivered over HTTP.'),
('FFmpeg','媒体处理工具','解码 编码 缩放 重采样及媒体分发处理。','A tool for decoding, encoding, scaling, resampling and media processing.'),
('MediaMTX','媒体分发器','在本地发布 RTSP 等媒体接口。','A local server publishing RTSP and other media interfaces.'),
('PCM16','数字声音','每个声音样本用 16 位整数表示。','Sound represented with 16-bit integer samples.'),
('Opus','声音压缩格式','把声音压缩后送过网络。','An audio codec for compressed network transport.'),
('WAV','声音文件容器','带音频格式说明的文件，可存 PCM。','An audio file container with format metadata; can contain PCM.'),
('Sample rate','采样率','每秒声音样本数，Hz，不等于音量。','Sound samples per second, in Hz; not volume.'),
('Frame / chunk / delta','帧 块 增量','都指片段，但各环节片段大小与含义不同。','Pieces whose sizes and meanings differ by pipeline stage.'),
('Buffer / queue','缓冲与队列','临时保存等待消费的数据，过多会增加延迟。','Temporary data awaiting consumption; excess buffering adds delay.'),
('JSON / JSONL','结构化文字','对象字段格式，以及每行一个对象的日志格式。','Structured objects, and a log format with one object per line.'),
('Base64','二进制转文本','让二进制装进文字消息，不是加密。','Represents binary bytes as text; not encryption.'),
('WebSocket / WSS','持续双向连接','保持一条连接收发事件；WSS 使用 TLS 加密。','A persistent bidirectional event connection; WSS adds TLS.'),
('VAD / AEC / AGC','语音检测 回声消除 自动增益','三个不同处理目标，不能互相替代。','Speech detection, echo cancellation and gain control are different jobs.'),
('Prompt','提示词','指导模型角色与行为的文本。','Text guiding the model’s role and behavior.'),
('Session / item / response','会话 条目 回答生成','分别是会话环境、内容单元与一次生成。','The session environment, a content unit and a generation operation.'),
('Token / context','计量单位与上下文','模型处理单位与当前可参考的内容。','Model processing units and currently available reference content.'),
('Truncate / handoff','截断与交接','删除未听到或过旧内容，或用摘要衔接新会话。','Trim content, or carry summarized context into a new session.'),
('Docker / Compose','容器与编排清单','运行隔离服务及声明服务之间的关系。','Run isolated services and declare how they relate.'),
('Bind mount','目录挂载','把宿主文件夹映射进容器，使文件保留。','Maps a host folder into a container for persistence.'),
('Health check','健康检查','验证连接与新数据状态，不等于听感验收。','Checks connection and data freshness, not physical listening quality.'),
('Fallback / backoff','降级与退避','改走备用路径，或失败后逐步延长重试间隔。','Use a backup path, or progressively space retries after failure.')]

SOURCES=[
('S1','compose.yaml','services / networks / ports / volumes','服务、网络、端口与环境转发','Services, networking, ports and environment wiring'),
('S2','realtime-assistant/app.py','Config / RealtimeClient / Speaker / MediaCapture','主助手全部运行链路','Main assistant runtime'),
('S3','ha-enabot/ebo/ebo_bridge.py','connect_agora / _start_audio_tx / _activate_pcm_stream','设备会话、PCM 提交与 Agora APM','Device session, PCM submission and Agora APM'),
('S4','ha-enabot/ebo/ebo_video.py','VideoPipeline / _start_ffmpeg / _pack_plane','视频转码、Opus 与媒体分发','Video conversion, Opus and media distribution'),
('S5','ha-enabot/ebo/run.sh','pget / pbool / process supervisor','Engine 参数优先级与启动监督','Engine setting precedence and process supervision'),
('S6','scripts/prepare-ebo.ps1','options generation','私有 options.json 的生成默认值','Generated private options.json defaults'),
('S7','realtime-assistant/app.py','MotionGate._prepare / MotionGate.observe','运动检测具体算法','Motion detection algorithm'),
('S8','realtime-assistant/app.py','add_visual_context / _handle_item_added','图片确认、替换和上下文消息','Image acknowledgment, replacement and context messages'),
('S9','ha-enabot/ebo/pcm_talk.py','PcmStream / PcmTalkServer','流握手、重采样、帧队列与进度','Streaming handshake, resampling, queues and progress'),
('S10','realtime-assistant/app.py','_on_open / _handle_session_updated','VAD 与会话字段的实际发送和确认','VAD/session fields sent and confirmed'),
('S11','realtime-assistant/app.py','_handle_input_transcript / _is_actionable_transcript','最终转写门控与去重','Final transcription gating and deduplication'),
('S12','scripts/reload-ebo-assistant-prompt.ps1','container recreation workflow','Prompt 与助手参数应用','Applying prompts and assistant settings'),
('S13','docs/barge-in-echo-handoff.zh-CN.md','2026-09-02 incident evidence','历史插话回声误触发证据；需结合当前代码','Historical echo-interruption evidence, interpreted with current code'),
('S14','docs/realtime-session-env.zh-CN.md','session parameter mapping','参数说明与固定协议边界','Parameter guide and fixed protocol boundaries'),
('S15','realtime-assistant/app.py','_rotation_step / _request_handoff / _recent_dialogue_memory / _on_close','计划轮换与意外恢复','Planned rotation and unplanned recovery'),
('S16','realtime-assistant/app.py','TranscriptStore / AssistantOutputStore / SessionMemoryLog','文件持久化及记忆日志','Persistence and memory logs'),
('S17','realtime-assistant/app.py','RuntimeState.snapshot / make_http_handler','健康状态与 HTTP 文件服务','Health status and HTTP file serving'),
('S18','scripts/apply-ebo-audio-settings.ps1','audio processing apply workflow','Engine AEC 开关应用与验证流程','Applying and verifying Engine AEC switches'),
('S19','ha-enabot/ebo/ha_integration/custom_components/ebo/','coordinator.py / camera.py / media_player.py','HA 状态、摄像头和扬声器适配','HA state, camera and speaker adapters'),
('S20','realtime-assistant/requirements.txt','dependency pins','NumPy OpenCV WebSocket WebRTC VAD 版本','Pinned NumPy, OpenCV, WebSocket and WebRTC VAD versions')]
WEB=[
('O1','GPT Realtime 2.1 Mini','https://developers.openai.com/api/docs/models/gpt-realtime-2.1-mini','图片输入与模型容量','Image modality and model capacity'),
('O2','Realtime conversations','https://developers.openai.com/api/docs/guides/realtime-conversations','会话寿命、音频增量、截断与交接机制','Session lifetime, audio increments, truncation and conversation mechanisms'),
('O3','Realtime client events','https://developers.openai.com/api/reference/resources/realtime/client-events','会话字段、音频格式和上下文限制','Session fields, audio formats and context limits'),
('O4','Voice activity detection','https://developers.openai.com/api/docs/guides/realtime-vad','VAD 工作方式','VAD behavior')]
